export const api = [
  {
    Investigation: "Primary Sample Type",
    Result: "Blood",
    Ref_Value: "",
    Unit: "",
  },
  {
    Investigation: <b>HEMOGLOBIN</b>,
    Result: "",
    Ref_Value: "",
    Unit: "",
  },
  {
    Investigation: "hemoglobin(HB)",
    Result: "12.5",
    Ref_Value: "Low 13.0-17.0",
    Unit: "g/dl",
  },
  {
    Investigation: <b>RBC COUNT</b>,
    Result: "",
    Ref_Value: "",
    Unit: "",
  },
  {
    Investigation: "Total RBC count",
    Result: "5.2",
    Ref_Value: "4.5-5.5",
    Unit: "mill/cumm",
  },
  {
    Investigation: <b>BLOOD INDICES</b>,
    Result: "",
    Ref_Value: "",
    Unit: "",
  },
  {
    Investigation: "Packed Cell Volume (PVC)",
    Result: "3.7",
    Ref_Value: "Low 40-50",
    Unit: "%",
  },
  {
    Investigation: "Mean Corpuscular Volume",
    Result: "72.12",
    Ref_Value: "50-62",
    Unit: "%",
  },
  {
    Investigation: "Calculated",
    Result: "",
    Ref_Value: "",
    Unit: "",
  },
  {
    Investigation: "RDW",
    Result: "13.6",
    Ref_Value: "11.6-14.0",
    Unit: "%",
  },
  {
    Investigation: <b>WBC COUNT</b>,
    Result: "",
    Ref_Value: "",
    Unit: "",
  },
  {
    Investigation: "Total WBC Count",
    Result: "9000",
    Ref_Value: "4000-11000",
    Unit: "cumm",
  },
  {
    Investigation: <b>DIFFERENTIAL WBC COUNT</b>,
    Result: "",
    Ref_Value: "",
    Unit: "",
  },
  {
    Investigation: "Neutrophils",
    Result: "60",
    Ref_Value: "50-62",
    Unit: "%",
  },
  {
    Investigation: "Lymphocytes",
    Result: "31",
    Ref_Value: "20-40",
    Unit: "%",
  },
  {
    Investigation: "Eosinophils",
    Result: "1",
    Ref_Value: "00-06",
    Unit: "%",
  },
  {
    Investigation: "Monocytes",
    Result: "7",
    Ref_Value: "00-10",
    Unit: "%",
  },
  {
    Investigation: "Basophils",
    Result: "1",
    Ref_Value: "00-02",
    Unit: "%",
  },
  {
    Investigation: <b>PLATELET</b>,
    Result: "",
    Ref_Value: "",
    Unit: "",
  },
  {
    Investigation: "Platelet Count",
    Result: "320000",
    Ref_Value: "150000-410000",
    Unit: "cumm",
  },
];
